# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install    
    displayName: 'poc install dependencies'

- script: npm run build:staging  
  displayName: 'poc staging build'
- task: ArchiveFiles@2
  inputs:  
    rootFolderOrFile: '$(Build.BinariesDirectory)/build' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/poc-staging/build.zip'
    replaceExistingArchive: true 
  displayName: 'poc staging zip files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/poc-staging'
    ArtifactName: 'poc-staging'
  displayName: 'poc staging publish to pipeline'

